[package]
name = "wcr"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
assert_cmd = "2.0.10"
clap = "4.1.14"
predicates = "3.0.2"
rand = "0.8.5"
